import Head from 'next/head'
import Nav from './Navbar'
import Footer from './Footer'

export default function Layout ({ children, title = 'Checa y Cuadra' }) {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Nav />
      {children}
      <Footer />
    </>
  )
}
